apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        #   # Para usar un rol de IAM asociado a un ServiceAccount en EKS, descomenta las siguientes líneas y comenta las líneas de secretRef
        #   # (esto es para que el pod pueda asumir el rol de IAM y obtener
        #   # credenciales temporales automáticamente, sin tener que poner keys fijas en el
        # serviceAccountRef:
        #   name: aws-autenticacion-postgres

        secretRef: # KEYS harcodeadas para el acceso temporal
          accessKeyIDSecretRef:
            name: aws-keys
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-keys
            key: AWS_SECRET_ACCESS_KEY
