apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-result
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/AgustinLandriel/gitops-voting-app.git
    targetRevision: HEAD
    path: k8s/result
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
