apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
spec:
  refreshInterval: 1h # cada cuánto revisa AWS por cambios
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: postgres-secret # el nombre del Secret de K8s que va a CREAR
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER # la clave en el Secret de K8s
      remoteRef:
        key: voting-app # el secreto en AWS
        property: POSTGRES_USER # qué campo del JSON de AWS
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: voting-app
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: voting-app
        property: POSTGRES_DB

# AWS Secrets Manager: voting-app/postgres (el JSON con las 3 credenciales)
#       ↓ ESO lo lee (vía el SecretStore)
# ExternalSecret: mapea cada property del JSON
#       ↓ ESO crea automáticamente
# Secret de K8s: postgres-secret (con POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB)
#       ↓ tu Deployment lo consume (envFrom, sin cambios)
# El pod de database arranca con las credenciales de AWS
